/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bbb.model.impl;

import com.liferay.bbb.model.MeetingParticipant;
import com.liferay.bbb.model.MeetingParticipantModel;
import com.liferay.bbb.model.MeetingParticipantSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MeetingParticipant service. Represents a row in the &quot;BBB_MeetingParticipant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.bbb.model.MeetingParticipantModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MeetingParticipantImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see MeetingParticipantImpl
 * @see com.liferay.bbb.model.MeetingParticipant
 * @see com.liferay.bbb.model.MeetingParticipantModel
 * @generated
 */
@JSON(strict = true)
public class MeetingParticipantModelImpl extends BaseModelImpl<MeetingParticipant>
	implements MeetingParticipantModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a meeting participant model instance should use the {@link com.liferay.bbb.model.MeetingParticipant} interface instead.
	 */
	public static final String TABLE_NAME = "BBB_MeetingParticipant";
	public static final Object[][] TABLE_COLUMNS = {
			{ "meetingParticipantId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "meetingEntryId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "emailAddress", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table BBB_MeetingParticipant (meetingParticipantId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,meetingEntryId LONG,name VARCHAR(75) null,emailAddress VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table BBB_MeetingParticipant";
	public static final String ORDER_BY_JPQL = " ORDER BY meetingParticipant.meetingParticipantId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY BBB_MeetingParticipant.meetingParticipantId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.bbb.model.MeetingParticipant"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.bbb.model.MeetingParticipant"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.bbb.model.MeetingParticipant"),
			true);
	public static long MEETINGENTRYID_COLUMN_BITMASK = 1L;
	public static long MEETINGPARTICIPANTID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MeetingParticipant toModel(MeetingParticipantSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MeetingParticipant model = new MeetingParticipantImpl();

		model.setMeetingParticipantId(soapModel.getMeetingParticipantId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMeetingEntryId(soapModel.getMeetingEntryId());
		model.setName(soapModel.getName());
		model.setEmailAddress(soapModel.getEmailAddress());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MeetingParticipant> toModels(
		MeetingParticipantSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MeetingParticipant> models = new ArrayList<MeetingParticipant>(soapModels.length);

		for (MeetingParticipantSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.bbb.model.MeetingParticipant"));

	public MeetingParticipantModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _meetingParticipantId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMeetingParticipantId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _meetingParticipantId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MeetingParticipant.class;
	}

	@Override
	public String getModelClassName() {
		return MeetingParticipant.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("meetingParticipantId", getMeetingParticipantId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("meetingEntryId", getMeetingEntryId());
		attributes.put("name", getName());
		attributes.put("emailAddress", getEmailAddress());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long meetingParticipantId = (Long)attributes.get("meetingParticipantId");

		if (meetingParticipantId != null) {
			setMeetingParticipantId(meetingParticipantId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long meetingEntryId = (Long)attributes.get("meetingEntryId");

		if (meetingEntryId != null) {
			setMeetingEntryId(meetingEntryId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String emailAddress = (String)attributes.get("emailAddress");

		if (emailAddress != null) {
			setEmailAddress(emailAddress);
		}
	}

	@JSON
	@Override
	public long getMeetingParticipantId() {
		return _meetingParticipantId;
	}

	@Override
	public void setMeetingParticipantId(long meetingParticipantId) {
		_meetingParticipantId = meetingParticipantId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMeetingEntryId() {
		return _meetingEntryId;
	}

	@Override
	public void setMeetingEntryId(long meetingEntryId) {
		_columnBitmask |= MEETINGENTRYID_COLUMN_BITMASK;

		if (!_setOriginalMeetingEntryId) {
			_setOriginalMeetingEntryId = true;

			_originalMeetingEntryId = _meetingEntryId;
		}

		_meetingEntryId = meetingEntryId;
	}

	public long getOriginalMeetingEntryId() {
		return _originalMeetingEntryId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@JSON
	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_emailAddress = emailAddress;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MeetingParticipant.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MeetingParticipant toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MeetingParticipant)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MeetingParticipantImpl meetingParticipantImpl = new MeetingParticipantImpl();

		meetingParticipantImpl.setMeetingParticipantId(getMeetingParticipantId());
		meetingParticipantImpl.setGroupId(getGroupId());
		meetingParticipantImpl.setCompanyId(getCompanyId());
		meetingParticipantImpl.setUserId(getUserId());
		meetingParticipantImpl.setUserName(getUserName());
		meetingParticipantImpl.setCreateDate(getCreateDate());
		meetingParticipantImpl.setModifiedDate(getModifiedDate());
		meetingParticipantImpl.setMeetingEntryId(getMeetingEntryId());
		meetingParticipantImpl.setName(getName());
		meetingParticipantImpl.setEmailAddress(getEmailAddress());

		meetingParticipantImpl.resetOriginalValues();

		return meetingParticipantImpl;
	}

	@Override
	public int compareTo(MeetingParticipant meetingParticipant) {
		long primaryKey = meetingParticipant.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MeetingParticipant)) {
			return false;
		}

		MeetingParticipant meetingParticipant = (MeetingParticipant)obj;

		long primaryKey = meetingParticipant.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		MeetingParticipantModelImpl meetingParticipantModelImpl = this;

		meetingParticipantModelImpl._originalMeetingEntryId = meetingParticipantModelImpl._meetingEntryId;

		meetingParticipantModelImpl._setOriginalMeetingEntryId = false;

		meetingParticipantModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MeetingParticipant> toCacheModel() {
		MeetingParticipantCacheModel meetingParticipantCacheModel = new MeetingParticipantCacheModel();

		meetingParticipantCacheModel.meetingParticipantId = getMeetingParticipantId();

		meetingParticipantCacheModel.groupId = getGroupId();

		meetingParticipantCacheModel.companyId = getCompanyId();

		meetingParticipantCacheModel.userId = getUserId();

		meetingParticipantCacheModel.userName = getUserName();

		String userName = meetingParticipantCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			meetingParticipantCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			meetingParticipantCacheModel.createDate = createDate.getTime();
		}
		else {
			meetingParticipantCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			meetingParticipantCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			meetingParticipantCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		meetingParticipantCacheModel.meetingEntryId = getMeetingEntryId();

		meetingParticipantCacheModel.name = getName();

		String name = meetingParticipantCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			meetingParticipantCacheModel.name = null;
		}

		meetingParticipantCacheModel.emailAddress = getEmailAddress();

		String emailAddress = meetingParticipantCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			meetingParticipantCacheModel.emailAddress = null;
		}

		return meetingParticipantCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{meetingParticipantId=");
		sb.append(getMeetingParticipantId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", meetingEntryId=");
		sb.append(getMeetingEntryId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", emailAddress=");
		sb.append(getEmailAddress());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.bbb.model.MeetingParticipant");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>meetingParticipantId</column-name><column-value><![CDATA[");
		sb.append(getMeetingParticipantId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>meetingEntryId</column-name><column-value><![CDATA[");
		sb.append(getMeetingEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>emailAddress</column-name><column-value><![CDATA[");
		sb.append(getEmailAddress());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = MeetingParticipant.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			MeetingParticipant.class
		};
	private long _meetingParticipantId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _meetingEntryId;
	private long _originalMeetingEntryId;
	private boolean _setOriginalMeetingEntryId;
	private String _name;
	private String _emailAddress;
	private long _columnBitmask;
	private MeetingParticipant _escapedModel;
}