/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.saml.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SamlIdpSpSession service. Represents a row in the &quot;SamlIdpSpSession&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.saml.model.impl.SamlIdpSpSessionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.saml.model.impl.SamlIdpSpSessionImpl}.
 * </p>
 *
 * @author Mika Koivisto
 * @see SamlIdpSpSession
 * @see com.liferay.saml.model.impl.SamlIdpSpSessionImpl
 * @see com.liferay.saml.model.impl.SamlIdpSpSessionModelImpl
 * @generated
 */
public interface SamlIdpSpSessionModel extends AuditedModel,
	BaseModel<SamlIdpSpSession> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a saml idp sp session model instance should use the {@link SamlIdpSpSession} interface instead.
	 */

	/**
	 * Returns the primary key of this saml idp sp session.
	 *
	 * @return the primary key of this saml idp sp session
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this saml idp sp session.
	 *
	 * @param primaryKey the primary key of this saml idp sp session
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the saml idp sp session ID of this saml idp sp session.
	 *
	 * @return the saml idp sp session ID of this saml idp sp session
	 */
	public long getSamlIdpSpSessionId();

	/**
	 * Sets the saml idp sp session ID of this saml idp sp session.
	 *
	 * @param samlIdpSpSessionId the saml idp sp session ID of this saml idp sp session
	 */
	public void setSamlIdpSpSessionId(long samlIdpSpSessionId);

	/**
	 * Returns the company ID of this saml idp sp session.
	 *
	 * @return the company ID of this saml idp sp session
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this saml idp sp session.
	 *
	 * @param companyId the company ID of this saml idp sp session
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this saml idp sp session.
	 *
	 * @return the user ID of this saml idp sp session
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this saml idp sp session.
	 *
	 * @param userId the user ID of this saml idp sp session
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this saml idp sp session.
	 *
	 * @return the user uuid of this saml idp sp session
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this saml idp sp session.
	 *
	 * @param userUuid the user uuid of this saml idp sp session
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this saml idp sp session.
	 *
	 * @return the user name of this saml idp sp session
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this saml idp sp session.
	 *
	 * @param userName the user name of this saml idp sp session
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this saml idp sp session.
	 *
	 * @return the create date of this saml idp sp session
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this saml idp sp session.
	 *
	 * @param createDate the create date of this saml idp sp session
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this saml idp sp session.
	 *
	 * @return the modified date of this saml idp sp session
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this saml idp sp session.
	 *
	 * @param modifiedDate the modified date of this saml idp sp session
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the saml idp sso session ID of this saml idp sp session.
	 *
	 * @return the saml idp sso session ID of this saml idp sp session
	 */
	public long getSamlIdpSsoSessionId();

	/**
	 * Sets the saml idp sso session ID of this saml idp sp session.
	 *
	 * @param samlIdpSsoSessionId the saml idp sso session ID of this saml idp sp session
	 */
	public void setSamlIdpSsoSessionId(long samlIdpSsoSessionId);

	/**
	 * Returns the saml sp entity ID of this saml idp sp session.
	 *
	 * @return the saml sp entity ID of this saml idp sp session
	 */
	@AutoEscape
	public String getSamlSpEntityId();

	/**
	 * Sets the saml sp entity ID of this saml idp sp session.
	 *
	 * @param samlSpEntityId the saml sp entity ID of this saml idp sp session
	 */
	public void setSamlSpEntityId(String samlSpEntityId);

	/**
	 * Returns the name ID format of this saml idp sp session.
	 *
	 * @return the name ID format of this saml idp sp session
	 */
	@AutoEscape
	public String getNameIdFormat();

	/**
	 * Sets the name ID format of this saml idp sp session.
	 *
	 * @param nameIdFormat the name ID format of this saml idp sp session
	 */
	public void setNameIdFormat(String nameIdFormat);

	/**
	 * Returns the name ID value of this saml idp sp session.
	 *
	 * @return the name ID value of this saml idp sp session
	 */
	@AutoEscape
	public String getNameIdValue();

	/**
	 * Sets the name ID value of this saml idp sp session.
	 *
	 * @param nameIdValue the name ID value of this saml idp sp session
	 */
	public void setNameIdValue(String nameIdValue);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(SamlIdpSpSession samlIdpSpSession);

	public int hashCode();

	public CacheModel<SamlIdpSpSession> toCacheModel();

	public SamlIdpSpSession toEscapedModel();

	public SamlIdpSpSession toUnescapedModel();

	public String toString();

	public String toXmlString();
}