/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.bbb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MeetingEntry service. Represents a row in the &quot;BBB_MeetingEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.bbb.model.impl.MeetingEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.bbb.model.impl.MeetingEntryImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see MeetingEntry
 * @see com.liferay.bbb.model.impl.MeetingEntryImpl
 * @see com.liferay.bbb.model.impl.MeetingEntryModelImpl
 * @generated
 */
public interface MeetingEntryModel extends BaseModel<MeetingEntry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a meeting entry model instance should use the {@link MeetingEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this meeting entry.
	 *
	 * @return the primary key of this meeting entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this meeting entry.
	 *
	 * @param primaryKey the primary key of this meeting entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the meeting entry ID of this meeting entry.
	 *
	 * @return the meeting entry ID of this meeting entry
	 */
	public long getMeetingEntryId();

	/**
	 * Sets the meeting entry ID of this meeting entry.
	 *
	 * @param meetingEntryId the meeting entry ID of this meeting entry
	 */
	public void setMeetingEntryId(long meetingEntryId);

	/**
	 * Returns the group ID of this meeting entry.
	 *
	 * @return the group ID of this meeting entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this meeting entry.
	 *
	 * @param groupId the group ID of this meeting entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this meeting entry.
	 *
	 * @return the company ID of this meeting entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this meeting entry.
	 *
	 * @param companyId the company ID of this meeting entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this meeting entry.
	 *
	 * @return the user ID of this meeting entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this meeting entry.
	 *
	 * @param userId the user ID of this meeting entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this meeting entry.
	 *
	 * @return the user uuid of this meeting entry
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this meeting entry.
	 *
	 * @param userUuid the user uuid of this meeting entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this meeting entry.
	 *
	 * @return the user name of this meeting entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this meeting entry.
	 *
	 * @param userName the user name of this meeting entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this meeting entry.
	 *
	 * @return the create date of this meeting entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this meeting entry.
	 *
	 * @param createDate the create date of this meeting entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this meeting entry.
	 *
	 * @return the modified date of this meeting entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this meeting entry.
	 *
	 * @param modifiedDate the modified date of this meeting entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the meeting server ID of this meeting entry.
	 *
	 * @return the meeting server ID of this meeting entry
	 */
	public long getMeetingServerId();

	/**
	 * Sets the meeting server ID of this meeting entry.
	 *
	 * @param meetingServerId the meeting server ID of this meeting entry
	 */
	public void setMeetingServerId(long meetingServerId);

	/**
	 * Returns the name of this meeting entry.
	 *
	 * @return the name of this meeting entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this meeting entry.
	 *
	 * @param name the name of this meeting entry
	 */
	public void setName(String name);

	/**
	 * Returns the attendee password of this meeting entry.
	 *
	 * @return the attendee password of this meeting entry
	 */
	@AutoEscape
	public String getAttendeePassword();

	/**
	 * Sets the attendee password of this meeting entry.
	 *
	 * @param attendeePassword the attendee password of this meeting entry
	 */
	public void setAttendeePassword(String attendeePassword);

	/**
	 * Returns the moderator password of this meeting entry.
	 *
	 * @return the moderator password of this meeting entry
	 */
	@AutoEscape
	public String getModeratorPassword();

	/**
	 * Sets the moderator password of this meeting entry.
	 *
	 * @param moderatorPassword the moderator password of this meeting entry
	 */
	public void setModeratorPassword(String moderatorPassword);

	/**
	 * Returns the status of this meeting entry.
	 *
	 * @return the status of this meeting entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this meeting entry.
	 *
	 * @param status the status of this meeting entry
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MeetingEntry meetingEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MeetingEntry> toCacheModel();

	@Override
	public MeetingEntry toEscapedModel();

	@Override
	public MeetingEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}